services:
  postgres:
    image: postgres:17.6
    container_name: receive_database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - receive_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: receive_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - receive_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receive_backend
    restart: unless-stopped
    command: bash -c "/commands/run_migrations.sh && /commands/run_web_server_dev.sh"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./app:/app
    networks:
      - receive_net

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receive_worker
    restart: unless-stopped
    command: celery -A core.celery.client worker --loglevel=info
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./app:/app
    networks:
      - receive_net

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receive_beat
    restart: unless-stopped
    command: celery -A core.celery.client beat --loglevel=info
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app
    networks:
      - receive_net

volumes:
  pg_data:
    name: receive_pg_data

networks:
  receive_net:
    driver: bridge