"""fix geo unique constraint

Revision ID: 537feb7eab73
Revises: d62c49126587
Create Date: 2026-01-17 11:44:59.263828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537feb7eab73'
down_revision: Union[str, Sequence[str], None] = 'd62c49126587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_geo_lat_lng', 'geo', ['lat', 'lng'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_geo_lat_lng', 'geo', type_='unique')
    # ### end Alembic commands ###
