"""add unique constraint to company name

Revision ID: d62c49126587
Revises: 48d96591ab7a
Create Date: 2026-01-17 11:07:35.273550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62c49126587'
down_revision: Union[str, Sequence[str], None] = '48d96591ab7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_companies_name'), 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_companies_name'), 'companies', type_='unique')
    # ### end Alembic commands ###
