"""Fix fields posts

Revision ID: f7f197142038
Revises: 1ba276e96034
Create Date: 2026-01-18 18:23:37.171992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f197142038'
down_revision: Union[str, Sequence[str], None] = '1ba276e96034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('userId', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_posts_user_id_users'), 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_posts_userId_users'), 'posts', 'users', ['userId'], ['id'])
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_posts_userId_users'), 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_posts_user_id_users'), 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'userId')
    # ### end Alembic commands ###
